name: examen-workflow

on:
  push:
    branches:
      - nueva-caracteristica

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4
      - name: Probar codigo
        run: python3 test.py
        
  build_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10' 
      - run: python test.py

  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/build-push-action@v6
        with:
          push: false
          tags: adrimr7/pruebaexamen:latest
